from django.urls import path

from . import views

urlpatterns = [
    path('userlist/', views.userlist),
    path('addUser/', views.addUser),
    path('addUserHandler/', views.addUserHandler),
    path('editUser/', views.editUser),
    path('editUserHandler/', views.editUserHandler),
    path('login/', views.login),
    path('loginHandler/', views.loginHandler),
    path('loginout/', views.loginout),
    path('homePage/', views.homePage),
    path('menuList/', views.menuList),
    path('addMenu/', views.addMenu),
    path('addMenuHandler/', views.addMenuHandler),
    path('delMenuHandler/', views.delMenuHandler),
    path('editMenu/', views.editMenu),
    path('editMenuHandler/', views.editMenuHandler),
    path('newsList/', views.newsList),
    path('delnews/', views.delnews),
    path('addNews/', views.addNews),
    path('addNewsHandler/', views.addNewsHandler),
    path('editNews/', views.editNews),
    path('editNewsHandler/', views.editNewsHandler),
    path('positionList/', views.positionList),
    path('addPosition/', views.addPosition),
    path('addPositionHandler/', views.addPositionHandler),
    path('editPosition/', views.editPosition),
    path('editPositionHandler/', views.editPositionHandler),
    path('delPosition/', views.delPosition),
    path('poscontent/', views.poscontent),
    path('addPosContent/', views.addPosContent),
    path('delPoscontent/', views.delPoscontent),
    path('editposContent/', views.editposContent),
    path('editposContentHandler/', views.editposContentHandler),
    path('clearFile/', views.clearFile),
]